name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  auto_route: 6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: 6.2.0
  build_runner: 2.3.3

flutter:
  fonts:
    - family: Mark Pro
      fonts:
        - asset: assets/fonts/MarkPro.ttf
        - asset: assets/fonts/MarkProBold.ttf
          weight: 700
        - asset: assets/fonts/MarkProMedium.ttf
          weight: 500
        - asset: assets/fonts/MarkProHeavy.ttf
          weight: 900


  uses-material-design: true
